import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Slider } from "@/components/ui/slider";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Play, Copy, Check, Loader2, Settings2, X } from "lucide-react";
import type { Model } from "./ModelCard";
import CodeBlock from "@/components/CodeBlock";

interface ModelPlaygroundProps {
  model: Model | null;
  onClose: () => void;
}

const ModelPlayground = ({ model, onClose }: ModelPlaygroundProps) => {
  const [prompt, setPrompt] = useState("");
  const [response, setResponse] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [temperature, setTemperature] = useState([0.7]);
  const [maxTokens, setMaxTokens] = useState([256]);
  const [copied, setCopied] = useState(false);

  if (!model) {
    return (
      <Card className="glass-card">
        <CardContent className="p-8 text-center text-muted-foreground">
          <Settings2 className="h-12 w-12 mx-auto mb-4 opacity-50" />
          <p className="text-lg font-medium mb-2">Select a Model</p>
          <p className="text-sm">Choose a model from the list to start testing in the playground.</p>
        </CardContent>
      </Card>
    );
  }

  const handleRun = async () => {
    if (!prompt.trim()) return;
    
    setIsLoading(true);
    setResponse("");

    // Simulate API response for demo
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    const mockResponses: Record<string, string> = {
      llm: `Based on your query, here's a comprehensive response generated by ${model.name}:\n\nThis is a demonstration of the model's capabilities. In production, this would connect to the actual inference API and return real model outputs with the specified parameters (temperature: ${temperature[0]}, max_tokens: ${maxTokens[0]}).`,
      "image-gen": `Image generation request processed by ${model.name}.\n\n[In production, this would return a generated image based on your prompt with resolution and style parameters applied.]`,
      vision: `Vision analysis by ${model.name}:\n\nThe model would analyze any uploaded images and provide detailed descriptions, object detection, or other visual understanding tasks.`,
      audio: `Audio processing by ${model.name}:\n\nThis model handles speech-to-text, text-to-speech, or audio analysis depending on the specific model variant selected.`,
      embedding: `Embedding vector generated by ${model.name}:\n\n[1024-dimensional vector representation of your input text for semantic search and similarity matching]`,
      code: `\`\`\`python\n# Code generated by ${model.name}\n\ndef hello_world():\n    """A simple function to demonstrate code generation."""\n    print("Hello from ReGraph!")\n    return True\n\nif __name__ == "__main__":\n    hello_world()\n\`\`\``,
      multimodal: `Multimodal analysis by ${model.name}:\n\nThis model can process and understand multiple input types (text, images, audio) and generate comprehensive responses.`,
    };

    setResponse(mockResponses[model.category] || mockResponses.llm);
    setIsLoading(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(response);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const curlExample = `curl -X POST https://api.regraph.tech/v1/inference \\
  -H "Authorization: Bearer rg_your_api_key" \\
  -H "Content-Type: application/json" \\
  -d '{
    "model": "${model.id}",
    "prompt": "${prompt.slice(0, 50)}${prompt.length > 50 ? "..." : ""}",
    "temperature": ${temperature[0]},
    "max_tokens": ${maxTokens[0]}
  }'`;

  return (
    <Card className="glass-card">
      <CardHeader className="flex flex-row items-start justify-between gap-4 pb-4">
        <div className="min-w-0 flex-1">
          <CardTitle className="text-xl flex items-center gap-2 flex-wrap">
            {model.name}
            <Badge variant="secondary">{model.provider}</Badge>
          </CardTitle>
          <p className="text-sm text-muted-foreground mt-1">{model.description}</p>
        </div>
        <Button 
          variant="ghost" 
          size="icon" 
          onClick={onClose}
          className="shrink-0 h-10 w-10 md:h-8 md:w-8"
        >
          <X className="h-5 w-5 md:h-4 md:w-4" />
        </Button>
      </CardHeader>

      <CardContent className="space-y-6">
        {/* Input */}
        <div>
          <Label htmlFor="prompt" className="mb-2 block">Prompt</Label>
          <Textarea
            id="prompt"
            placeholder={
              model.category === "image-gen" 
                ? "A futuristic cityscape at sunset, cyberpunk style, highly detailed..." 
                : model.category === "code"
                ? "Write a Python function that calculates the Fibonacci sequence..."
                : "Enter your prompt here..."
            }
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            className="min-h-[120px] resize-none"
          />
        </div>

        {/* Parameters */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <Label>Temperature</Label>
              <span className="text-sm text-muted-foreground">{temperature[0]}</span>
            </div>
            <Slider
              value={temperature}
              onValueChange={setTemperature}
              min={0}
              max={2}
              step={0.1}
              className="w-full"
            />
            <p className="text-xs text-muted-foreground">Controls randomness. Lower = more focused, higher = more creative.</p>
          </div>

          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <Label>Max Tokens</Label>
              <span className="text-sm text-muted-foreground">{maxTokens[0]}</span>
            </div>
            <Slider
              value={maxTokens}
              onValueChange={setMaxTokens}
              min={64}
              max={4096}
              step={64}
              className="w-full"
            />
            <p className="text-xs text-muted-foreground">Maximum length of the generated response.</p>
          </div>
        </div>

        {/* Run Button */}
        <Button 
          onClick={handleRun} 
          disabled={!prompt.trim() || isLoading}
          className="w-full glow-primary"
        >
          {isLoading ? (
            <>
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <Play className="h-4 w-4 mr-2" />
              Run Inference
            </>
          )}
        </Button>

        {/* Response */}
        {response && (
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>Response</Label>
              <Button variant="ghost" size="sm" onClick={handleCopy}>
                {copied ? (
                  <Check className="h-4 w-4 text-green-500" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </Button>
            </div>
            <div className="bg-secondary/50 rounded-lg p-4 text-sm whitespace-pre-wrap">
              {response}
            </div>
          </div>
        )}

        {/* API Example */}
        <div className="space-y-2">
          <Label>API Request</Label>
          <CodeBlock code={curlExample} language="bash" />
        </div>
      </CardContent>
    </Card>
  );
};

export default ModelPlayground;
